# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michiel Tiller
tagline:          'Michiels ramblings'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://michiel.tiller.nl

author:
  name:           'Michiel Tiller'
  url:            https://twitter.com/M1ch13Lt

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mchlt/
