# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Michiel Tiller
tagline:          'Michiels ramblings'
description:      'Not much here in this menu yet.'
url:              http://michiel.tiller.nl

author:
  name:           'Michiel Tiller'
  url:            https://twitter.com/M1ch13Lt

paginate:         5

# Custom vars
#version:          2.0.0

github:
  repo:           https://github.com/mchlt/

